In [7]:
from google.colab import files
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
%matplotlib inline
uploaded = files.upload()
spam_rf_filename = next(iter(uploaded))
s_rf = pd.read_csv(io.StringIO(uploaded[spam_rf_filename].decode('utf-8')))
s_rf.head()

Saving spam_rf.csv to spam_rf.csv

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_req_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,spam
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

In [8]:
from sklearn.model_selection import train_test_split
features = s_rf.columns.drop('spam')
target = "spam"
X=s_rf[features]
Y=s_rf[target]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [9]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 10, min_samples_split=20,min_impurity_decrease=0.05)
model.fit(X_train,Y_train)
train_accuracy = model.score(X_train,Y_train)
test_accuracy = model.score(X_test,Y_test)
print("Train Accuracy= ",train_accuracy)
print("Test Accuracy= ",test_accuracy)

Train Accuracy=  0.8304347826086956
Test Accuracy=  0.7893593919652552

In [10]:
feature_imps = pd.DataFrame(np.array([features,
                                      model.feature_importances_]).T,
                            columns=["feature","importance"])
feature_imps.sort_values(by="importance",ascending=False)

                       feature importance
22               word_freq_000   0.222222
52                 char_freq_$   0.222222
51                 char_freq_!   0.151698
10           word_freq_receive   0.111111
23             word_freq_money   0.111111
15              word_freq_free   0.068519
55  capital_run_length_longest   0.065879
6             word_freq_remove   0.024014
56    capital_run_length_total   0.023223
49                 char_freq_(        0.0
50                 char_freq_[        0.0
33               word_freq_415        0.0
34                word_freq_85        0.0
35        word_freq_technology        0.0
36              word_freq_1999        0.0
37             word_freq_parts        0.0
38                word_freq_pm        0.0
54  capital_run_length_average        0.0
53                 char_freq_#        0.0
39            word_freq_direct        0.0
40                word_freq_cs        0.0
41           word_freq_meeting        0.0
42          word_freq_original        0.0
43           word_freq_project        0.0
44                word_freq_re        0.0
31               word_freq_857        0.0
45               word_freq_edu        0.0
46             word_freq_table        0.0
47        word_freq_conference        0.0
48                 char_freq_;        0.0
32              word_freq_data        0.0
0               word_freq_make        0.0
30            word_freq_telnet        0.0
14         word_freq_addresses        0.0
2                word_freq_all        0.0
3                 word_freq_3d        0.0
4                 word_req_our        0.0
5               word_freq_over        0.0
7           word_freq_internet        0.0
8              word_freq_order        0.0
9               word_freq_mail        0.0
11              word_freq_will        0.0
12            word_freq_people        0.0
13            word_freq_report        0.0
16          word_freq_business        0.0
29              word_freq_labs        0.0
17             word_freq_email        0.0
18               word_freq_you        0.0
19            word_freq_credit        0.0
20              word_freq_your        0.0
21              word_freq_font        0.0
24                word_freq_hp        0.0
25               word_freq_hpl        0.0
26            word_freq_george        0.0
27               word_freq_650        0.0
1            word_freq_address        0.0
28               word_freq_lab        0.0

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier(n_estimators=10)
model.fit(X_train,Y_train)
train_accuracy = model.score(X_train,Y_train)
test_accuracy = model.score(X_test,Y_test)
print("Train Accuracy= ",train_accuracy)
print("Test Accuracy= ",test_accuracy)

Train Accuracy=  0.9059782608695652
Test Accuracy=  0.8946796959826275